name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
        
    - name: Test container
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
        docker run -d -p 5000:5000 --name test-container ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
        sleep 5
        curl http://localhost:5000
