name: Docker CI/CD with Versioning

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - main

env:
  VERSION_FILE: version.txt

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper versioning
    
    - name: Get current version
      id: version
      run: |
        if [ -f "${{ env.VERSION_FILE }}" ]; then
          current_version=$(cat "${{ env.VERSION_FILE }}")
          echo "Current version: $current_version"
        else
          current_version="1.0.0"
          echo "No version file found. Starting with version: $current_version"
          echo "$current_version" > "${{ env.VERSION_FILE }}"
        fi
        echo "current_version=$current_version" >> $GITHUB_OUTPUT
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      id: build_push
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:${{ steps.version.outputs.current_version }}
          ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest
    
    - name: Increment version on successful build
      if: success()
      id: increment_version
      run: |
        # Parse current version
        current_version="${{ steps.version.outputs.current_version }}"
        IFS='.' read -r major minor patch <<< "$current_version"
        
        # Increment patch version
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"
        
        echo "New version: $new_version"
        echo "$new_version" > "${{ env.VERSION_FILE }}"
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
    
    - name: Commit and push version update
      if: success() && github.event_name == 'push'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add "${{ env.VERSION_FILE }}"
        git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }}"
        git push
